# Minimal stubs for net-ntlm types used by the gem
module Net
  module NTLM
    class Message
      def self.parse: (untyped) -> Net::NTLM::Message
      def response: (?Hash[Symbol, untyped], ?Hash[Symbol, untyped]) -> Net::NTLM::Message
    end

    class Message::Type1
      def serialize: () -> String
    end

    def self.encode_utf16le: (String) -> String
  end
end

